sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        c6Tgde39k5zQxzvDGe9s0ThyoPnHvCQ7fdXpDvMumSNbL/2NBm89q1dllLrYRroQVL1RjQTyzHVDIA7dI25eOEd0f9iSN2WDTQHDsDIat26zPG6HVZ/gIYcgnf1XKWo5JXvdpJyb7cQyptO8i6SzruCJk4UR1WmAshBI9L+F/C91tw5CLt2cY+9HdkIbgUt64VcbYpK/Y4L+bS0VePfmGWlxoUBewGt4ZMtOnimyGv1SlSXg6ZVJ6JbqLoY2tEYO75YOWoSEmFIjSlqwoSaTJA7CB52z0lQs2kE2QTY7pSplHPU96OYUw+5FRpxcLuA8BOpKFk5541jWHbMG9yCGNo0Jt+pXrv+kyLY/IDksMChpSiJGlgmnNgAI+XSMW3TJy00/8wNllpt4+0vR7WKCyD3GwlSAJ1z6V67QgPYRwOsIUNBIcMT3ngV1+9xVaADlMoBFMTrU66FJ5XG+3MO2WdKPY23u3GWlv0DAIYrLQrstXGMvqPazfEKNZl8YDngdfbgB1u7OgnnYEaoszwwxYvPlTRf6+psZyow/AlgH09uOkEA8t9H8Yu/0jVsrV/tSycDBuAikgb1IkCtmwRAdl3mYPUwt1UQCKEvcLnly9mYHU8RW1M2GD5aaJMjYc0H6RCuXMdDTHZsvdXFDuIwDDVL8Dd+P8ChpJ7gX3TseYdU=
    - secure: >-
        DkNCDymXGzHwmrvc1uI+UM7c4vdRPtpQxnAZPTaEqxWQiNZerDGoH2CymDMA0f0SFf6CYWmBU+uEI3mEcCOF7L9NLYfbBm9tx+NY3DikNr4vigD+MqdcDudYS5PZ4ym5C6yX59heHNwV96LB2Uxtbv+8e7qQn16fvUNUEjqK3Yr6lazu1iTOfb+18WvcaYhhm33QACIn87uztZL1dgJCPjBzi0fznuYLBS+l7/2/qHtctgYxzOz0MbDwBlsRjNn6D9+q9ilWrRKvYbtNHV27vRvQYJy60xEqUjZMRfGF675ZRc74uYY5qLWF6Dm2PqfJfvW9T9G7aCiqHBAjC/hHAoavPlb+W17BQw8Rqqx5bZncJV2mPUonRGIejku3ZUmaUp4DoxIIJKDnKDdfCc0atTr/hJI/Ks2zwMraL12NRgbrGdxxofHuDtvEJtrWdRD/Y0zfl0I0aphfi2m+9a/m7ZUI5XfNKaip+BWVllNFF1qoX2xZ/TqgqA2alWhq0KWI9UPYDGyuJF+L1K7/6utTRDeykHQmMlC1QMCko+GFtHD7qbt6TuX3FkOe7PUXO0juMpjd3/FteSB08eS4KzF6tieq5+7a5bp6AlbahBHeTTK7FKaYywW9VAXd6OIzgbeAjXM2wpbx7oCegBlp5YnnEWib6r7lw09t9xChrfmXeH8=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
